In [21]:
import pandas as pd
# Reading in my census data -- race by zip code
# Source: https://censusreporter.org/data/table/?table=B02001&geo_ids=04000US26,860|04000US26&primary_geo_id=04000US26#
df = pd.read_csv("csv/acs2019-race-zip-michigan-raw.csv")

In [22]:
df

,geoid,name,B02001001,"B02001001, Error",B02001002,"B02001002, Error",B02001003,"B02001003, Error",B02001004,"B02001004, Error",...,B02001006,"B02001006, Error",B02001007,"B02001007, Error",B02001008,"B02001008, Error",B02001009,"B02001009, Error",B02001010,"B02001010, Error"
0,04000US26,Michigan,9965265,0,7813755,4058,1374314,4050,53316,1913,...,3099,339,117801,3429,291259,5445,26495,1502,264764,5124
1,86000US48001,48001,11903,92,11547,179,12,15,67,55,...,13,20,83,79,110,85,0,16,110,85
2,86000US48002,48002,3224,32,3183,44,0,10,0,10,...,0,10,0,10,41,28,6,9,35,28
3,86000US48003,48003,6047,179,5967,185,1,4,8,13,...,0,15,0,15,13,16,0,15,13,16
4,86000US48005,48005,5509,20,5341,82,42,49,21,33,...,0,15,0,15,95,54,16,25,79,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,86000US49969,49969,1259,138,885,116,8,12,312,60,...,2,3,0,10,26,30,0,10,26,30
986,86000US49970,49970,292,68,289,67,0,10,0,10,...,0,10,0,10,3,4,0,10,3,4
987,86000US49971,49971,478,87,455,83,0,10,8,7,...,0,10,0,10,2,6,0,10,2,6
988,86000US54540,54540,916,155,907,153,0,12,4,5,...,0,12,0,12,5,7,1,2,4,7
989,86000US54554,54554,1043,132,976,135,10,22,18,18,...,0,12,0,12,27,18,0,12,27,18

In [23]:
# Getting a percentage of the total for each column except population, name and geojson info
cols = ['B02001001, Error','B02001002', 'B02001002, Error', 'B02001003', 'B02001003, Error','B02001004','B02001004, Error','B02001005', 'B02001005, Error','B02001006','B02001006, Error','B02001007','B02001007, Error','B02001008','B02001008, Error','B02001009','B02001009, Error','B02001010','B02001010, Error']
df[cols] = df[cols].div(df['B02001001'], axis=0).multiply(100).round(1)

In [24]:
df

,geoid,name,B02001001,"B02001001, Error",B02001002,"B02001002, Error",B02001003,"B02001003, Error",B02001004,"B02001004, Error",...,B02001006,"B02001006, Error",B02001007,"B02001007, Error",B02001008,"B02001008, Error",B02001009,"B02001009, Error",B02001010,"B02001010, Error"
0,04000US26,Michigan,9965265,0.0,78.4,0.0,13.8,0.0,0.5,0.0,...,0.0,0.0,1.2,0.0,2.9,0.1,0.3,0.0,2.7,0.1
1,86000US48001,48001,11903,0.8,97.0,1.5,0.1,0.1,0.6,0.5,...,0.1,0.2,0.7,0.7,0.9,0.7,0.0,0.1,0.9,0.7
2,86000US48002,48002,3224,1.0,98.7,1.4,0.0,0.3,0.0,0.3,...,0.0,0.3,0.0,0.3,1.3,0.9,0.2,0.3,1.1,0.9
3,86000US48003,48003,6047,3.0,98.7,3.1,0.0,0.1,0.1,0.2,...,0.0,0.2,0.0,0.2,0.2,0.3,0.0,0.2,0.2,0.3
4,86000US48005,48005,5509,0.4,97.0,1.5,0.8,0.9,0.4,0.6,...,0.0,0.3,0.0,0.3,1.7,1.0,0.3,0.5,1.4,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,86000US49969,49969,1259,11.0,70.3,9.2,0.6,1.0,24.8,4.8,...,0.2,0.2,0.0,0.8,2.1,2.4,0.0,0.8,2.1,2.4
986,86000US49970,49970,292,23.3,99.0,22.9,0.0,3.4,0.0,3.4,...,0.0,3.4,0.0,3.4,1.0,1.4,0.0,3.4,1.0,1.4
987,86000US49971,49971,478,18.2,95.2,17.4,0.0,2.1,1.7,1.5,...,0.0,2.1,0.0,2.1,0.4,1.3,0.0,2.1,0.4,1.3
988,86000US54540,54540,916,16.9,99.0,16.7,0.0,1.3,0.4,0.5,...,0.0,1.3,0.0,1.3,0.5,0.8,0.1,0.2,0.4,0.8
989,86000US54554,54554,1043,12.7,93.6,12.9,1.0,2.1,1.7,1.7,...,0.0,1.2,0.0,1.2,2.6,1.7,0.0,1.2,2.6,1.7

In [25]:
# Renaming the columns
df = df.rename(columns={ "B02001001": "Total", "B02001002": "white_pct", "B02001003": "black_pct", "B02001004": "am_indian_ak_native_pct", "B02001005": "asian_pct", "B02001006": "hi_pc_islander_pct", "B02001007": "other_alone_pct", "B02001008": "two_more_pct", "B02001009": "two_other_pct", "B02001010": "two_three_pct"}, errors="raise")

In [26]:
# Renaming the error columns
df = df.rename(columns={ "B02001001, Error": "Total, Error", "B02001002, Error": "white_err", "B02001003, Error": "black_err", "B02001004, Error": "am_indian_ak_native_err", "B02001005, Error": "asian_err", "B02001006, Error": "hi_pc_islander_err", "B02001007, Error": "other_alone_err", "B02001008, Error": "two_more_err", "B02001009, Error": "two_other_err", "B02001010, Error": "two_three_err"}, errors="raise")
df

,geoid,name,Total,"Total, Error",white_pct,white_err,black_pct,black_err,am_indian_ak_native_pct,am_indian_ak_native_err,...,hi_pc_islander_pct,hi_pc_islander_err,other_alone_pct,other_alone_err,two_more_pct,two_more_err,two_other_pct,two_other_err,two_three_pct,two_three_err
0,04000US26,Michigan,9965265,0.0,78.4,0.0,13.8,0.0,0.5,0.0,...,0.0,0.0,1.2,0.0,2.9,0.1,0.3,0.0,2.7,0.1
1,86000US48001,48001,11903,0.8,97.0,1.5,0.1,0.1,0.6,0.5,...,0.1,0.2,0.7,0.7,0.9,0.7,0.0,0.1,0.9,0.7
2,86000US48002,48002,3224,1.0,98.7,1.4,0.0,0.3,0.0,0.3,...,0.0,0.3,0.0,0.3,1.3,0.9,0.2,0.3,1.1,0.9
3,86000US48003,48003,6047,3.0,98.7,3.1,0.0,0.1,0.1,0.2,...,0.0,0.2,0.0,0.2,0.2,0.3,0.0,0.2,0.2,0.3
4,86000US48005,48005,5509,0.4,97.0,1.5,0.8,0.9,0.4,0.6,...,0.0,0.3,0.0,0.3,1.7,1.0,0.3,0.5,1.4,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,86000US49969,49969,1259,11.0,70.3,9.2,0.6,1.0,24.8,4.8,...,0.2,0.2,0.0,0.8,2.1,2.4,0.0,0.8,2.1,2.4
986,86000US49970,49970,292,23.3,99.0,22.9,0.0,3.4,0.0,3.4,...,0.0,3.4,0.0,3.4,1.0,1.4,0.0,3.4,1.0,1.4
987,86000US49971,49971,478,18.2,95.2,17.4,0.0,2.1,1.7,1.5,...,0.0,2.1,0.0,2.1,0.4,1.3,0.0,2.1,0.4,1.3
988,86000US54540,54540,916,16.9,99.0,16.7,0.0,1.3,0.4,0.5,...,0.0,1.3,0.0,1.3,0.5,0.8,0.1,0.2,0.4,0.8
989,86000US54554,54554,1043,12.7,93.6,12.9,1.0,2.1,1.7,1.7,...,0.0,1.2,0.0,1.2,2.6,1.7,0.0,1.2,2.6,1.7

In [31]:
# Adding up the other columns
df['other_pct'] = df['other_alone_pct'] + df['two_more_pct']
df

,geoid,name,Total,"Total, Error",white_pct,white_err,black_pct,black_err,am_indian_ak_native_pct,am_indian_ak_native_err,...,other_alone_pct,other_alone_err,two_more_pct,two_more_err,two_other_pct,two_other_err,two_three_pct,two_three_err,other_pct,total_check
0,04000US26,Michigan,9965265,0.0,78.4,0.0,13.8,0.0,0.5,0.0,...,1.2,0.0,2.9,0.1,0.3,0.0,2.7,0.1,4.1,99.7
1,86000US48001,48001,11903,0.8,97.0,1.5,0.1,0.1,0.6,0.5,...,0.7,0.7,0.9,0.7,0.0,0.1,0.9,0.7,1.6,100.0
2,86000US48002,48002,3224,1.0,98.7,1.4,0.0,0.3,0.0,0.3,...,0.0,0.3,1.3,0.9,0.2,0.3,1.1,0.9,1.3,99.8
3,86000US48003,48003,6047,3.0,98.7,3.1,0.0,0.1,0.1,0.2,...,0.0,0.2,0.2,0.3,0.0,0.2,0.2,0.3,0.2,100.0
4,86000US48005,48005,5509,0.4,97.0,1.5,0.8,0.9,0.4,0.6,...,0.0,0.3,1.7,1.0,0.3,0.5,1.4,0.9,1.7,99.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,86000US49969,49969,1259,11.0,70.3,9.2,0.6,1.0,24.8,4.8,...,0.0,0.8,2.1,2.4,0.0,0.8,2.1,2.4,2.1,100.1
986,86000US49970,49970,292,23.3,99.0,22.9,0.0,3.4,0.0,3.4,...,0.0,3.4,1.0,1.4,0.0,3.4,1.0,1.4,1.0,100.0
987,86000US49971,49971,478,18.2,95.2,17.4,0.0,2.1,1.7,1.5,...,0.0,2.1,0.4,1.3,0.0,2.1,0.4,1.3,0.4,100.0
988,86000US54540,54540,916,16.9,99.0,16.7,0.0,1.3,0.4,0.5,...,0.0,1.3,0.5,0.8,0.1,0.2,0.4,0.8,0.5,99.8
989,86000US54554,54554,1043,12.7,93.6,12.9,1.0,2.1,1.7,1.7,...,0.0,1.2,2.6,1.7,0.0,1.2,2.6,1.7,2.6,100.1

In [28]:
# Does everything add up?
# Seems like it, I think because of error, it might not add up always perfectly to 100
# would check with Census data expert on this before publishing
df['total_check'] = df['white_pct'] + df['black_pct'] + df['am_indian_ak_native_pct'] + df['asian_pct'] + df['hi_pc_islander_pct'] + df['other_pct']

In [29]:
df

,geoid,name,Total,"Total, Error",white_pct,white_err,black_pct,black_err,am_indian_ak_native_pct,am_indian_ak_native_err,...,other_alone_pct,other_alone_err,two_more_pct,two_more_err,two_other_pct,two_other_err,two_three_pct,two_three_err,other_pct,total_check
0,04000US26,Michigan,9965265,0.0,78.4,0.0,13.8,0.0,0.5,0.0,...,1.2,0.0,2.9,0.1,0.3,0.0,2.7,0.1,3.9,99.7
1,86000US48001,48001,11903,0.8,97.0,1.5,0.1,0.1,0.6,0.5,...,0.7,0.7,0.9,0.7,0.0,0.1,0.9,0.7,1.6,100.0
2,86000US48002,48002,3224,1.0,98.7,1.4,0.0,0.3,0.0,0.3,...,0.0,0.3,1.3,0.9,0.2,0.3,1.1,0.9,1.1,99.8
3,86000US48003,48003,6047,3.0,98.7,3.1,0.0,0.1,0.1,0.2,...,0.0,0.2,0.2,0.3,0.0,0.2,0.2,0.3,0.2,100.0
4,86000US48005,48005,5509,0.4,97.0,1.5,0.8,0.9,0.4,0.6,...,0.0,0.3,1.7,1.0,0.3,0.5,1.4,0.9,1.4,99.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,86000US49969,49969,1259,11.0,70.3,9.2,0.6,1.0,24.8,4.8,...,0.0,0.8,2.1,2.4,0.0,0.8,2.1,2.4,2.1,100.1
986,86000US49970,49970,292,23.3,99.0,22.9,0.0,3.4,0.0,3.4,...,0.0,3.4,1.0,1.4,0.0,3.4,1.0,1.4,1.0,100.0
987,86000US49971,49971,478,18.2,95.2,17.4,0.0,2.1,1.7,1.5,...,0.0,2.1,0.4,1.3,0.0,2.1,0.4,1.3,0.4,100.0
988,86000US54540,54540,916,16.9,99.0,16.7,0.0,1.3,0.4,0.5,...,0.0,1.3,0.5,0.8,0.1,0.2,0.4,0.8,0.4,99.8
989,86000US54554,54554,1043,12.7,93.6,12.9,1.0,2.1,1.7,1.7,...,0.0,1.2,2.6,1.7,0.0,1.2,2.6,1.7,2.6,100.1

In [33]:
# Making a copy with the columns that I want and exporting it to a csv
df[['name','white_pct', 'black_pct','am_indian_ak_native_pct','asian_pct','hi_pc_islander_pct','other_pct']].copy().to_csv("csv/acs2019-race-zip-michigan-clean.csv",index=False)

In [15]:
# Reading in my census data --- poverty
# Source: https://censusreporter.org/data/table/?table=B17001&geo_ids=04000US26,860|04000US26&primary_geo_id=04000US26
df2 = pd.read_csv("csv/acs2019-poverty-zip-michigan-raw.csv")

In [16]:
# Making a copy with the columns I want
df2 = df2[['name', 'B17001001', 'B17001001, Error','B17001002','B17001002, Error']].copy()
df2

         name  B17001001  B17001001, Error  B17001002  B17001002, Error
0    Michigan    9741628              1788    1398527             14569
1       48001      11818               102       1173               239
2       48002       3212                34        246               112
3       48003       6047               179        567               195
4       48005       5439                93        265               107
..        ...        ...               ...        ...               ...
985     49969       1258               138        185                59
986     49970        285                66         22                21
987     49971        478                87         54                27
988     54540        916               155         97                45
989     54554        991               129        124                71

[990 rows x 5 columns]

In [17]:
# Renaming the columns
df2 = df2.rename(columns={"B17001001":"Total","B17001001, Error": "Total, Error", "B17001002": "Income Poverty Level","B17001002, Error": "Income Poverty Level, Error"})

In [18]:
df2

,name,Total,"Total, Error",Income Poverty Level,"Income Poverty Level, Error"
0,Michigan,9741628,1788,1398527,14569
1,48001,11818,102,1173,239
2,48002,3212,34,246,112
3,48003,6047,179,567,195
4,48005,5439,93,265,107
...,...,...,...,...,...
985,49969,1258,138,185,59
986,49970,285,66,22,21
987,49971,478,87,54,27
988,54540,916,155,97,45
989,54554,991,129,124,71

In [19]:
# Getting percentage of the total
# Exporting to csv
cols = ['Total, Error', 'Income Poverty Level', 'Income Poverty Level, Error']
df2[cols] = df2[cols].div(df2['Total'], axis=0).multiply(100).round(1)
df2.to_csv("csv/acs2019-poverty-zip-michigan-clean.csv")